/* CONECTANDO A UM BANCO */

USE EMPRESA
GO

/* CRIAÇÃO DE TABELAS */

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE
)
GO

/* CONSTRAINTS */

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

/* FAZENDO RELACIONAMENTO 1 x 1 */ 

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE
)
GO

/* CRIANDO A FK */

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* COMANDO DE DESCRIÇÃO (DESC, SHOW) =
PROCEDURES JA CRIADAS E ARMAZENADAS NO SISTEMA */

SP_COLUMNS ALUNO -- COMANDO PARA DESCRIÇÃO DA TABELA 
GO

SP_HELP ALUNO -- DESCRIÇÃO BEM MAIS DETALHADA
GO

/* INSERINDO DADOS */

INSERT INTO ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO ALUNO VALUES('ANA','F','1978/03/09','ANA@IG.COM')
INSERT INTO ALUNO VALUES('RUI','M','1951/09/09','RUI@IG.COM')
INSERT INTO ALUNO VALUES('JAO','M','2002/12/09','JAO@IG.COM')
GO

SELECT * FROM ALUNO
GO

/* INSERINDO DADOS NA TABELA ENDEREÇO */
INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO ENDERECO VALUES('CENTRO','MG',4)
INSERT INTO ENDERECO VALUES('CENTRO','SP',3)
GO

/* CRIANDO A TABELA TELEFONES 1 x N*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN ('RES','COM','CEL'))

)
GO

INSERT INTO TELEFONE VALUES('CEL','7899889',1)
INSERT INTO TELEFONE VALUES('RES','4325444',1)
INSERT INTO TELEFONE VALUES('COM','4354354',2)
INSERT INTO TELEFONE VALUES('CEL','2344556',2)
GO

/* COMANDO PARA PEGAR DATA ATUAL */

SELECT GETDATE()
GO

/* CLAUSULA AMBIGUA */

SELECT A.NOME, T.TIPO, T.NUMERO, E.BAIRRO, E.UF
FROM ALUNO A 
INNER JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E 
ON A.IDALUNO = E.ID_ALUNO 
GO

SELECT A.NOME, T.TIPO, T.NUMERO, E.BAIRRO, E.UF
FROM ALUNO A LEFT JOIN TELEFONE T -- RETORNA TODOS OS ALUNOS ATÉ SEM TELEFONE
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E 
ON A.IDALUNO = E.ID_ALUNO 
GO

/* IFNULL */

SELECT 
	A.NOME, 
	ISNULL (T.TIPO,'SEM') AS "TIPO", 
	ISNULL (T.NUMERO, 'NUMERO') AS "TELEFONE", 
	E.BAIRRO, 
	E.UF
FROM ALUNO A LEFT JOIN TELEFONE T -- RETORNA TODOS OS ALUNOS ATÉ SEM TELEFONE
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E 
ON A.IDALUNO = E.ID_ALUNO 
GO

/* DATAS */

SELECT * FROM ALUNO
GO

SELEC NOME, NASCIMENTO
FROM ALUNO
GO

/* DATEDIFF - CALCULA A DIFERENÇA ENTRE 2 DATAS 
FUNÇÃO GETDATE() TRAZ DIA E HORA
*/

SELECT NOME, GETDATE() AS DIA_HORA FROM ALUNO
GO

/* 1 PASSO COM DATEDIFF */

SELECT NOME, DATEDIFF(DAY,NASCIMENTO,GETDATE())
FROM ALUNO
GO


/* 2 PASSO */

SELECT NOME, DATEDIFF(DAY,NASCIMENTO,GETDATE()) AS "IDADE"
FROM ALUNO
GO



/* 3 PASSO - RETORN EM INTEIRO + OPER. MATEMATICA */

SELECT NOME, (DATEDIFF(DAY,NASCIMENTO,GETDATE())/356) AS "IDADE"
FROM ALUNO
GO

SELECT NOME, (DATEDIFF(MONTH,NASCIMENTO,GETDATE())/356) AS "IDADE"
FROM ALUNO
GO

SELECT NOME, DATEDIFF(YEAR,NASCIMENTO,GETDATE()) AS "IDADE"
FROM ALUNO
GO

/* DATENAME - TRAZ O NOME DA PARTE DA DATA EM QUESTÃO - STRING */

SELECT NOME, DATENAME(MONTH,NASCIMENTO) AS "MÊS"
FROM ALUNO
GO

SELECT NOME, DATENAME(YEAR,NASCIMENTO) AS "ANO"
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY,NASCIMENTO) AS "DIA DA SEMANA"
FROM ALUNO
GO

/* DATEPART - POREM RETORNA NUMERO INTEIRO */

SELECT NOME, DATEPART(MONTH,NASCIMENTO), DATENAME(MONTH,NASCIMENTO)
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMANDO-A OUTRA DATA */

SELECT DATEADD(DAY, 365, GETDATE())
GO

SELECT DATEADD(YEAR, 10, GETDATE())
GO

/* CONVERSÃO DE DADOS */

SELECT 1 + '1'
GO

SELECT '1' + '1'
GO

SELECT 'CURSO DE BANCO DE DADOS' + '1'
GO

SELECT 'CURSO DE BANCO DE DADOS' + 1 -- DA ERRO POIS O BANCO NÃO CONSEGUE FAZER A CONVERSÃO 
GO

/* FUNÇÕES DE CONVERSÃO DE DADOS */

SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO


/* CONVERSÃO E CONCATENAÇÃO */

SELECT NOME,
NASCIMENTO
FROM ALUNO
GO

/* EXERCICIO -- FAÇA A CONVERSÃO CORRETA DA DATA ABAIXO */

SELECT NOME,
DAY(NASCIMENTO) + '/' + 
MONTH(NASCIMENTO) + '/' + 
YEAR(NASCIMENTO)
FROM ALUNO
GO

/* CORREÇÃO */

SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(YEAR(NASCIMENTO) AS VARCHAR) AS NASCIMENTO
FROM ALUNO
GO


/* CHARINDEX - RETORNA UM NUMERO INTEIRO 
CONTAGEM DEFAULT - INICIA EM 01 
 */

SELECT NOME, CHARINDEX('A', NOME) AS INDICE
FROM ALUNO 
GO 

SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE
FROM ALUNO 
GO 

/* BULK INSERT IMPORTAÇÃO DE ARQUIVOS  - */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEBITO_CREDITO CHAR(1)
)
GO 

SELECT * FROM LANCAMENTO_CONTABIL
GO

BULK INSERT LANCAMENTO_CONTABIL
FROM 'D:\CONTAS.txt'
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'char'
	FIELDTERMINATOR = '\t'
	ROWTERMINATOR = '\n'
)
GO

/* DESAFIO DO SALDO 
FAÇA UMA QUERY QUE TRAGA NUMERO DA CONTA 
SALDO - DEVEDOR OU CREDOR  */