/* ALTERANDO TABLEAS */

CREATE TABLE TABELA (
    COLUNA1 VARCHAR(30),
    COLUNA2 VARCHAR(30),
    COLUNA3 VARCHAR(30)
);

CREATE TABLE TABELA(
    COLUNA1 INT PRIMARY KEY AUTO_INCREMENT
); -- NÃO FUNCIONA

/* ADICIONANDO UMA PK (PRIMARY KEY) */

ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1);

/* ADICIONANDO UMA COLUNA COM POSICAO */

ALTER TABLE TABELA 
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3; -- ESSE AFTER DEFINE ONDE VAI ENTRAR A TABELA

/* ADICIONANDO COLUNA SEM POSICAO. ULTIMA POSICAO */

ALTER TABLE TABELA 
ADD COLUNA VARCHAR(30);

/* MODIFICANDO O TIPO DE UM CAMPO */

ALTER TABLE TABELA 
 MODIFY COLUNA2 DATE NOT NULL;

/* RENOMEANDO O NOME DA TABELA */

ALTER TABLE TABELA
RENAME PESSOA;

/* CRIANDO TABEL E ADICIONANDO A FK (FOREING KEY) */

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/* VERIFICAR AS CHAVES */

SHOW CREATE TABLE TIME;

/* ORGANIZANDO CHAVES - CONSTRAINT (REGRA) */

CREATE TABLE JOGADOR(
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);

CREATE TABLE TIMES (
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_JOGADOR INT,
    FOREIGN KEY(ID_JOGADOR)
    REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR VALUES(NULL,'GUERRERO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;

/* ORGANIZANDO CHAVES */
USE COMERCIO;

SHOW TABLES;

DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE TELEFONE;