/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

DELIMITER $

CREATE PROCEDURE CONS_CURSO(P_IDCURSO INT)
BEGIN

    SELECT IDCURSO, NOME, HORAS, VALOR FROM CURSOS
    WHERE IDCURSO = P_IDCURSO;

END$

DELIMITER ;

CALL CONS_CURSO(2);

DROP PROCEDURE CONS_CURSO;