/* fazendo requerimento de NOME, EMAIL, NUMERO, ESTADO */

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E 
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T 
    ON C.IDCLIENTE = T.ID_CLIENTE;

IFNULL()

SELECT C.NOME, 
       IFNULL(C.EMAIL, '************') AS "E-MAIL", 
       E.ESTADO, 
       T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E 
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T 
    ON C.IDCLIENTE = T.ID_CLIENTE;