 /* DICIONARIO DE DADOS */

SHOW DATABASES;

USE INFORMATION_SCHEMA;

STATUS -- use para verificar onde você está conectado

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
        CONSTRAINT_NAME AS "NOME REGRA",
        CONSTRAINT_TYPE AS "TIPO"
        FROM TABLE_CONSTRAINTS;



SELECT CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
        CONSTRAINT_NAME AS "NOME REGRA",
        CONSTRAINT_TYPE AS "TIPO"
        FROM TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = 'COMERCIO';