/* MODELAGEM FISICA */

CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    ID_VEICULO INT UNIQUE
);

CREATE TABLE TELEFONES(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(5),
    NUMERO VARCHAR(11),
    ID_CLIENTE INT
);

CREATE TABLE VEICULO (
    IDVEICULO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    ID_MARCA INT 
);

CREATE TABLE MARCAS (
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) NOT NULL UNIQUE
);    

CREATE TABLE CORES_DO_CARRO(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(30) NOT NULL
);

CREATE TABLE CARRO_COR(
    ID_VEICULO INT,
    ID_COR INT,
    PRIMARY KEY(ID_VEICULO,ID_COR)
);


ALTER TABLE TELEFONES 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_VEICULO
FOREIGN KEY(ID_VEICULO)
REFERENCES VEICULO(IDVEICULO);

ALTER TABLE VEICULO
ADD CONSTRAINT FK_VEICULO_MARCAS
FOREIGN KEY(ID_MARCA)
REFERENCES MARCAS(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES CORES_DO_CARRO(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_VEICULO
FOREIGN KEY(ID_VEICULO)
REFERENCES VEICULO(IDVEICULO);

/* PREENCHENDO DADOS */

DELIMITER $

CREATE PROCEDURE INSERT_MARCAS(P_MARCA VARCHAR(30))
BEGIN

    INSERT INTO MARCAS VALUES (NULL, P_MARCA);

END
$

CREATE PROCEDURE INSERT_VEICULO(P_MODELO VARCHAR(30),
                                P_PLACA VARCHAR(10)
                                P_ID_MARCA INT)
BEGIN

    INSERT INTO VEICULO VALUES (NULL, P_MODELO, P_PLACA, P_ID_MARCA);

END
$

CREATE PROCEDURE INSERT_CLIENTE(P_NOME VARCHAR(30),
                                P_SEXO CHAR(1)
                                P_ID_VEICULO INT)
BEGIN

    INSERT INTO CLIENTE VALUES (NULL, P_NOME, P_SEXO, P_ID_VEICULO);

END
$
