/* STORED PROCEDURES */

DELIMITER $ -- ANTES DE COMEÇAR, TROQUE O DELIMITER PARA NÃO DAR ERRO

/* ESTRUTURA BASICA DE UMA PROCEDURE */

CREATE PROCEDURE NOME()
BEGIN

    QUALQUER PROGRAMAÇÃO;

END
$

/* CRIANDO UMA REAL */ 

DELIMITER $

CREATE PROCEDURE NOME_EMPRESA()
BEGIN

    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;

END
$

/* CHAMANDO UMA PROCEDURE */

CALL NOME_EMPRESA()$

DELIMITER ; -- PODE VOLTAR O DELIMITADOR PARA O PADRÃO DEPOIS DE CRIAR UMA PROCEDURE 

CALL NOME_EMPRESA();

/* CRIANDO UMA PROCEDURE COM PARAMETROS */

DELIMITER $

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN

    SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100,50)$