/* STORED PROCEDURES */

DELIMITER $ -- ANTES DE COMEÇAR, TROQUE O DELIMITER PARA NÃO DAR ERRO

/* ESTRUTURA BASICA DE UMA PROCEDURE */

CREATE PROCEDURE NOME()
BEGIN

    QUALQUER PROGRAMAÇÃO;

END
$

/* CRIANDO UMA REAL */ 

DELIMITER $

CREATE PROCEDURE NOME_EMPRESA()
BEGIN

    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;

END
$

/* CHAMANDO UMA PROCEDURE */

CALL NOME_EMPRESA()$

DELIMITER ; -- PODE VOLTAR O DELIMITADOR PARA O PADRÃO DEPOIS DE CRIAR UMA PROCEDURE 

CALL NOME_EMPRESA();

/* CRIANDO UMA PROCEDURE COM PARAMETROS */

DELIMITER $

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN

    SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100,50)$

/* CRIANDO UMA PROCEDURE FUNCIONAL */

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);

DELIMITER $

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), 
                           P_HORAS INT(3),
                           P_PRECO FLOAT(10,2))
BEGIN

    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);

END
$

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('POWER BI',20,1000.00);
CALL CAD_CURSO('TABLEAU',30,1200.00);